#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=15

CONF="uuplugin"
PROG="/var/tmp/uu/uuplugin"
UU_CONF="/var/tmp/uu/uu.conf"
UU_INFO="/var/tmp/uu/h3c_info"
UU_SN="/tmp/haiapi"
armuurl="https://router.uu.163.com/api/plugin?type=h3c-bx54"
#armuurl="https://router.uu.163.com/api/plugin?type=h3c-ne36"
aarch64uurl="https://router.uu.163.com/api/plugin?type=h3c-nx30pro"
#mipsuurl="https://router.uu.163.com/api/plugin?type=h3c-nx15"
#mipseluurl="https://router.uu.163.com/api/plugin?type=h3c"
mipseluurl="https://router.uu.163.com/api/plugin?type=jd-hr06"
SN=$(ip addr show br-lan | grep "link/ether" | awk '{print $2}')

start_service() {
	echo "经测试：此定制版UU加速器在FW3 iptables环境和FW4 nftables环境里加速都有效！"
	echo "有问题可前往 https://github.com/lmq8267/luci-app-uugamebooster/issues 反馈。"
        config_load "$CONF"
	local enabled 
	#config_get_bool enabled "$CONF" "enabled" "0"
	enabled="$(uci -q get uuplugin.@uuplugin[0].enabled)"
	echo "UU=$enabled"
	[ -z "$enabled" ] && enabled=0
	[ "$enabled" -eq "1" ] || return 1
	echo "start..."
	cputype=$(uname -ms | tr ' ' '_' | tr '[A-Z]' '[a-z]')
	[ -n "$(echo $cputype | grep -E "linux.*armv.*")" ] && cpucore="arm"
	[ -n "$(echo $cputype | grep -E "linux.*aarch64.*|linux.*armv8.*")" ] && cpucore="aarch64"
	if [ -n "$(echo $cputype | grep -E "linux.*mips.*")" ] ; then
           mipstype=$(echo -n I | hexdump -o 2>/dev/null | awk '{ print substr($2,6,1); exit}')
           [ "$mipstype" != "0" ] && cpucore="mipsel"
        fi
	if [ -z "$cpucore" ]; then
          echo "当前架构不符合，无法安装！此luci-app-uugamebooster安装包仅支持arm aarch64 mipsel架构！"
          uci -q set uuplugin.@uuplugin[0].enabled=0
          exit 1
        fi
        local model
	#config_get model "uuplugin" "model" "OpenWrt"
	model="$(uci -q get uuplugin.@uuplugin[0].model)"
	echo "model=$model"
	[ -z "$model" ] && model="OpenWrt"
	mkdir -p /var/tmp/uu
	if [ "$cpucore" = "mipsel" ]; then
		# jd系列需要haiapi
		echo "部署京东定制版UU运行环境..."
		echo "#!/bin/sh" > $UU_SN
		echo "echo '{\"result\": [ {\"data\": { \"mac\": \"$SN\", \"model\": \"$model\" }, \"code\": \"0x0\" } ] }'" >> $UU_SN
		[ ! -L /usr/bin/haiapi ] && ln -sf $UU_SN /usr/bin/haiapi
		chmod u+x $UU_SN
	else
		echo "部署H3C定制版UU运行环境..."
		echo "productname=$model" >$UU_INFO
		echo "ethaddr=$SN" >>$UU_INFO
		echo "hardversion=VER.A" >>$UU_INFO
		echo "bootversion=100" >>$UU_INFO
		echo "manucode=$SN" >>$UU_INFO
	fi
	if [ ! -e "$PROG" ] || [ ! -e "$UU_CONF" ] ; then
	  echo "开始下载主程序..."
	  local uuurl=""
	  case "$cpucore" in
	    arm)
	      uuurl="$armuurl"
	      ;;
	    aarch64)
	      uuurl="$aarch64uurl"
	      ;;
	    mipsel)
	      uuurl="$mipseluurl"
	      ;;
	    *)
	      echo "不支持的架构: $cpucore"
	      return 1
	      ;;
	  esac
	  UU_url=$(curl -L -s -k -H "Accept:text/plain" "$uuurl" | wget --header=Accept:text/plain -q --no-check-certificate -O - "$uuurl" | curl -s -k -H "Accept:text/plain" "$uuurl")
	  if [ -z "$UU_url" ]; then
	    case "$cpucore" in
	      arm)
	        UU_url="http://uu.gdl.netease.com/uuplugin/h3c-bx54/v6.3.12/uu.tar.gz,56c6a0a5ed99c05d933091fc0b1c7d8c"
	        ;;
	      aarch64)
	        UU_url="http://uu.gdl.netease.com/uuplugin/h3c-nx30pro/v6.3.12/uu.tar.gz,059dda9bf2803fe3f32b1d48e6b5c6d3"
	        ;;
	      mipsel)
	        UU_url="http://uu.gdl.netease.com/uuplugin/jd-hr06/v6.3.10/uu.tar.gz,b4535b953b982bd8909d83da719e21b1"
	        ;;
	    esac
	  fi
	  plugin_url=$(echo "$UU_url" | cut  -d ',' -f 1)
	  plugin_md5=$(echo "$UU_url" | cut  -d ',' -f 2)
	  echo "下载$plugin_url 到/tmp/uu.tar.gz"
	  curl -L -s -k "$plugin_url" -o /tmp/uu.tar.gz >/dev/null 2>&1 || wget -q --no-check-certificate "$plugin_url" -O /tmp/uu.tar.gz >/dev/null 2>&1 || curl -s -k "$plugin_url" -o /tmp/uu.tar.gz >/dev/null 2>&1 
	  download_md5=$(md5sum /tmp/uu.tar.gz | awk '{print $1}')
	  if [ "$download_md5" != "$plugin_md5" ];then
            echo "下载的/tmp/uu.tar.gz不完整！"
            rm -rf /tmp/uu.tar.gz
            return 1
          else
            echo "下载完成，开始解压到$PROG"
            tar zxf /tmp/uu.tar.gz -C /var/tmp/uu
          fi
	  
	fi
	chmod u+x $PROG
	[ "$cpucore" = "mipsel" ] && chmod u+x /usr/bin/haiapi 2>/dev/null
        uu_ver=$($PROG -v | awk -F 'version:' '{print $2}' | tr -d ' \n')
        echo "开始启动 ${PROG}-${uu_ver}"
	procd_open_instance uuplugin

	procd_set_param command "$PROG" "$UU_CONF"

	procd_set_param limits core="unlimited"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1

	procd_close_instance
	echo "done"
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger uuplugin
}

